[package]
name = "rustimer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
color-eyre = "0.6.3"
crossterm = "0.28.1"
futures-util = "0.3.30"
ratatui = "0.28.1"
tokio = { version = "1", features = ["full"] }
zbus = "4.4.0"
zbus_macros = "4.4.0"
